#####################################################
#            Holidays Collections                   #
#####################################################

collections:
  Christmas Movies:
    sync_mode: append
    smart_label: release.desc
    sort_title: +02_Christmas
    summary: "A collection of festive-themed movies to get even the Grinchiest of hearts in the Christmas spirit"
    trakt_list: https://trakt.tv/users/yozoraxcii/lists/christmas-extravaganza-non-romance
    url_poster: https://theposterdb.com/api/assets/48897/view?
    url_background: https://wallpapercave.com/wp/wp4972414.jpg
    schedule: range(11/01-12/31)
    delete_not_scheduled: true
    visible_library: true
    visible_home: true
    visible_shared: true

  Halloween Movies:
    sync_mode: sync
    smart_label: random
    sort_title: +02_Halloween
    trakt_list:
      - https://trakt.tv/users/29zombies/lists/halloween
      - https://trakt.tv/users/galacticboy/lists/not-so-spooky-halloween
      - https://trakt.tv/users/triadcool/lists/halloween?sort=released,asc
      - https://trakt.tv/users/evil-vin/lists/halloween-2021?sort=released,asc
    summary: "A collection of spook films, make sure to check for monsters under your bed before you go to sleep!"
    url_poster: https://bit.ly/PlexSeasonHalloween
    schedule: range(10/01-11/01)
    visible_library: true
    visible_home: true
    visible_shared: true

  Valentine's Movies:
    sync_mode: sync
    smart_label: random
    sort_title: +02_Valentine
    trakt_list:
      - https://trakt.tv/users/triadcool/lists/valentine
    summary: "Forget Netflix and Chill, time to Plex and Chill"
    url_poster: https://m.media-amazon.com/images/I/61dbP+B8EfL._SL1000_.jpg
    schedule: range (02/01-02/14)
    visible_home: true
    visible_shared: true
    visible_library: true
