# This file is a template remove the .template to use the file

libraries:                                        # Library mappings must have a colon (:) placed after them
  Movies:
    report_path: config/missing/Movies_missing.yml
    template_variables:
      collection_mode: hide
    metadata_path:
    - git: PMM/award/bafta
      template_variables:
        data:
          starting: 2014
          ending: current_year
    - git: PMM/award/cannes
      template_variables:
        data:
          starting: 2016
          ending: current_year
    - git: PMM/award/choice
      template_variables:
        data:
          starting: 2014
          ending: current_year
    - git: PMM/award/golden
      template_variables:
        data:
          starting: 1943
          ending: current_year
    - git: PMM/award/oscars
      template_variables:
        data:
          starting: 1927
          ending: current_year
    - git: PMM/award/other
    - git: PMM/award/spirit
      template_variables:
        data:
          starting: 2014
          ending: current_year
    - git: PMM/award/sundance
      template_variables:
        data:
          starting: 2010
          ending: current_year
    - git: PMM/chart/anilist
    - git: PMM/chart/imdb
    - git: PMM/chart/myanimelist
    - git: PMM/chart/other
    - git: PMM/chart/tautulli
    - git: PMM/chart/tmdb
    - git: PMM/chart/trakt
    - git: PMM/chart/basic          # Keep this as the last chart item so that collection_mode: hide works properly on library tab for CHART COLLECTION
    - git: PMM/actor
      template_variables:
        style: bw
        data:
          depth: 5
          limit: 150
    - git: PMM/movie/director
      template_variables:
        style: bw
        data:
          depth: 5
          limit: 150
    - git: PMM/movie/producer
      template_variables:
        style: bw
        data:
          depth: 5
          limit: 150
    - git: PMM/movie/writer
      template_variables:
        style: bw
        data:
          depth: 5
          limit: 150
    - git: PMM/audio_language
    - git: PMM/movie/content_rating_us           # Choose content_rating_uk or content_rating_us
    - git: PMM/genre
    - git: PMM/resolution_standards              # Choose resolution_standards or resolution
    - git: PMM/studio
    - git: PMM/subtitle_language
    - git: PMM/year
      template_variables:
        data:
          starting: 1880
          ending: current_year
    - git: PMM/movie/country
    - git: PMM/movie/decade
    # - git: PMM/movie/franchise
      # template_variables:
        # minimum_items: 2
        # delete_below_minimum: true    
    - git: PMM/movie/seasonal
      template_variables:
        schedule_independence: daily
        schedule_easter: daily
        schedule_valentine: daily
        schedule_patrick: daily
        schedule_thanksgiving: daily
        schedule_halloween: daily
        schedule_christmas: daily
        schedule_years: daily
    - git: PMM/streaming
    - git: PMM/movie/universe
    overlay_path:
    - remove_overlays: false
    - reapply_overlay: true
    - git: PMM/overlays/audio_codec
      # template_variables:
        # style: standard
    - git: PMM/overlays/audio_language
    # - git: PMM/overlays/direct_play
    - git: PMM/overlays/imdb_top_250
      template_variables:
        weight: 30
    - git: PMM/overlays/mc_must_see
      template_variables:
        weight: 10
    - git: PMM/overlays/rt_cert_fresh
      template_variables:
        weight: 20
    - git: PMM/overlays/ratings
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/metadata/overlays/fonts/Impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating3_font_size: 70

        horizontal_position: right

        # rating_source: Anidb
        # font: config/metadata/overlays/fonts/Handel Gothic ITC W01 Heavy.ttf
        # rating_source: IMDb
        # font: config/metadata/overlays/fonts/Impact.ttf
        # rating_source: Letterboxd
        # font: config/metadata/overlays/fonts/HelveticaNowDisplay-ExtBlk.ttf
        # rating_source: Metacritic
        # font: config/metadata/overlays/fonts/Myriad Bold.otf
        # rating_source: TMDb
        # font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        # rating_source: Trakt
        # font: config/metadata/overlays/fonts/Claspo-ND-Medium.ttf
        # rating_source: Rotten
        # font: config/metadata/overlays/fonts/Adlib.ttf
    - git: PMM/overlays/resolution
    - git: PMM/overlays/special_release
    - git: PMM/overlays/streaming
    - git: PMM/overlays/video_format
    settings:
      asset_directory:
      - config/assets

    operations:
      split_duplicates: true
      assets_for_all: false
      delete_unmanaged_collections: true
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      mass_user_rating_update: mdb_tomatoesaudience
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_originally_available_update: tmdb
      mass_imdb_parental_labels: without_none

  TV Shows:
    report_path: config/missing/TV_missing.yml
    template_variables:
      collection_mode: hide
    metadata_path:
    - git: PMM/award/choice
      template_variables:
        data:
          starting: 2014
          ending: current_year
    - git: PMM/award/golden
      template_variables:
        data:
          starting: 1943
          ending: current_year
    - git: PMM/award/emmy
      template_variables:
        data:
          starting: 1947
          ending: current_year
    - git: PMM/chart/anilist
    - git: PMM/chart/imdb
    - git: PMM/chart/myanimelist
    - git: PMM/chart/other
    - git: PMM/chart/tautulli
    - git: PMM/chart/tmdb
    - git: PMM/chart/trakt
    - git: PMM/chart/basic          # Keep this as the last chart item so that collection_mode: hide works properly on library tab for CHART COLLECTION
    - git: PMM/actor
      template_variables:
        style: bw
        data:
          depth: 5
          limit: 150
    - git: PMM/audio_language
    - git: PMM/show/content_rating_us            # Choose content_rating_uk or content_rating_us
    - git: PMM/genre
    - git: PMM/resolution_standards              # Choose resolution_standards or resolution
    - git: PMM/studio
    - git: PMM/subtitle_language
    - git: PMM/year
      template_variables:
        data:
          starting: 1880
          ending: current_year
    - git: PMM/show/country
    - git: PMM/show/decade
    - git: PMM/show/network
    - git: PMM/streaming
    overlay_path:
    - remove_overlays: false
    - reapply_overlay: true
    - git: PMM/overlays/audio_codec
    - git: PMM/overlays/audio_codec
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/audio_codec
      template_variables:
        overlay_level: season
    - git: PMM/overlays/audio_language
    - git: PMM/overlays/audio_language
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/audio_language
      template_variables:
        overlay_level: season
    # - git: PMM/overlays/direct_play
    # - git: PMM/overlays/direct_play
      # template_variables:
        # overlay_level: episode
    # - git: PMM/overlays/direct_play
      # template_variables:
        # overlay_level: season
    - git: PMM/overlays/imdb_top_250
      template_variables:
        weight: 30
    - git: PMM/overlays/imdb_top_250
      template_variables:
        weight: 30
        overlay_level: season
    - git: PMM/overlays/imdb_top_250
      template_variables:
        weight: 30
        overlay_level: episode
    - git: PMM/overlays/mc_must_see
      template_variables:
        weight: 10
    - git: PMM/overlays/mc_must_see
      template_variables:
        weight: 10
        overlay_level: season
    - git: PMM/overlays/mc_must_see
      template_variables:
        weight: 10
        overlay_level: episode
    - git: PMM/overlays/rt_cert_fresh
      template_variables:
        weight: 20
    - git: PMM/overlays/rt_cert_fresh
      template_variables:
        weight: 20
        overlay_level: season
    - git: PMM/overlays/rt_cert_fresh
      template_variables:
        weight: 20
        overlay_level: episode
    - git: PMM/overlays/ratings
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/metadata/overlays/fonts/Impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating3_font_size: 70

        horizontal_position: right
    - git: PMM/overlays/ratings
      template_variables:
        # rating1: user
        # rating1_image: rt_tomato
        # rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        # rating1_font_size: 63

        rating1: critic
        rating1_image: imdb
        rating1_font: config/metadata/overlays/fonts/Impact.ttf
        rating1_font_size: 70

        rating2: audience
        rating2_image: tmdb
        rating2_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating2_font_size: 70

        horizontal_position: right
        overlay_level: episode
    # - file: config/metadata/overlays/ratings
      # template_variables:
        # # rating1: user
        # # rating1_image: rt_tomato
        # # rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        # # rating1_font_size: 63

        # rating2: critic
        # rating2_image: imdb
        # rating2_font: config/metadata/overlays/fonts/Impact.ttf
        # rating2_font_size: 70

        # rating3: audience
        # rating3_image: tmdb
        # rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        # rating3_font_size: 70

        # horizontal_position: right
        # side: right
        # overlay_level: season
    - git: PMM/overlays/resolution
    - git: PMM/overlays/resolution
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/resolution
      template_variables:
        overlay_level: season
    - git: PMM/overlays/special_release
    - git: PMM/overlays/special_release
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/special_release
      template_variables:
        overlay_level: season
    - git: PMM/overlays/streaming
    - git: PMM/overlays/streaming
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/streaming
      template_variables:
        overlay_level: season
    - git: PMM/overlays/video_format
    - git: PMM/overlays/video_format
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/video_format
      template_variables:
        overlay_level: season
    settings:
      asset_directory:
      - config/assets

    operations:
      split_duplicates: true
      assets_for_all: false
      delete_unmanaged_collections: true
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      mass_user_rating_update: mdb_tomatoesaudience
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_originally_available_update: tmdb
      mass_imdb_parental_labels: without_none
playlist_files:
- git: PMM/playlist
  template_variables:
    libraries: Movies, TV Shows
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  missing_path: config/missing
  asset_folders: true
  asset_depth: 3
  create_asset_folders: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: true
  show_options: true
  show_missing: false
  show_missing_assets: false
  save_missing: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  check_nightly: true
  playlist_report: true
  prioritize_assets: false
  save_report: false
  item_refresh_delay: 0
  playlist_sync_to_users: all
  verify_ssl: true
  custom_git:
  custom_repo:
webhooks:                                       # Can be individually specified per library as well
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  changes:
  - notifiarr
  version:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: (redacted)
  token: (redacted)
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
tmdb:                                           # REQUIRED for the script to run
  apikey: (redacted)
  language: en
  cache_expiration: 60
  region:
tautulli:                                       # Can be individually specified per library as well
  url: (redacted)
  apikey: (redacted)
omdb:
  apikey: (redacted)
  cache_expiration: 60
mdblist:
  apikey: (redacted)
  cache_expiration: 60
notifiarr:
  apikey: (redacted)
radarr:                                         # Can be individually specified per library as well
  url: (redacted)
  token: (redacted)
  root_folder_path: /data/media/movies
  monitor: true
  availability: announced
  quality_profile: Any
  tag: pmm
  search: false
  radarr_path:
  plex_path:
  add_existing: false
  add_missing: false
  upgrade_existing: false
sonarr:                                         # Can be individually specified per library as well
  url: (redacted)
  token: (redacted)
  root_folder_path: /data/media/tv
  monitor: all
  quality_profile: Any
  language_profile: English
  series_type: standard
  season_folder: true
  tag: pmm
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  add_existing: false
  add_missing: false
  upgrade_existing: false
############################################
trakt:
  client_id: (redacted)
  client_secret: (redacted)
  authorization:
    access_token: (redacted)
    token_type: Bearer
    expires_in: 7889237
    refresh_token: (redacted)
    scope: public
    created_at: 1658177504
  pin:
############################################      
mal:
  client_id: (redacted)
  client_secret: (redacted)
  authorization:
    access_token: (redacted)
    token_type: Bearer
    expires_in: 2678400
    refresh_token: (redacted)
  localhost_url:
