######################################################
#               Genre Collections                    #
######################################################

templates:
  genre:
    sort_title: +02_<<collection_name>>
    url_background: https://wallpaper.dog/large/20509069.jpg
    smart_filter:
      sort_by: release.desc
      validate: false
      all:
        genre.not: "children, animation, family"
        audio_language: english
        any:
          genre: <<genre>>
#    schedule: weekly (sunday)

collections:
  Cooking Shows:
    template: { name: genre, genre: "Food" }
    url_poster: https://i.imgur.com/VM2wr44.jpg

  Crime Shows:
    template: { name: genre, genre: "Crime" }
    url_poster: https://i.imgur.com/qXqvLTA.jpg

  Documentary Shows:
    template: { name: genre, genre: "Biography, Documentary" }
    url_poster: https://i.imgur.com/t4ltEIY.jpg

  Game Shows:
    template: { name: genre, genre: "Game Show" }
    smart_filter:
      sort_by: episode_added.desc
      validate: false
      all:
        genre.not: "children, animation"
        any:
          genre: "Game Show"
    url_poster: https://i.imgur.com/HGlAWyH.jpg

  Reality Shows:
    template: { name: genre, genre: "Reality" }
    url_poster: https://i.imgur.com/v4A3Up2.jpg