######################################################
#                Chart Collections                   #
######################################################
templates:
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
collections:
  Popular on Plex:
    template: { name: Chart, num: 1 }
    tautulli_popular:
      list_days: 30
      list_size: 20
      list_buffer: 20
    tautulli_watched:
      list_days: 30
      list_size: 20
      list_buffer: 20
    summary: Shows Popular on Plex
    url_poster: https://i.imgur.com/G5M442S.jpg