#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/other                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   anidb            AniDB Popular               #
#          #   commonsense      Common Sense Selected       #
#          #   stevenlu         StevenLu's Popular Movies   #
#          #   pirated          Top 10 Pirated Movies       #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          radarr_add_missing_key:                          #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

external_templates:
  git: PMM/templates
  template_variables:
    collection_section: "01"

templates:
  css:
    mdblist_list: https://mdblist.com/lists/plexmetamanager/cssfamilies<<library_type>>s
    summary: A collection of Common Sense <<library_type>>s. Common Sense recognizes outstanding entertainment with an official seal for quality and impact. Common Sense Selections include age-appropriate media with the potential to spark family conversations, entertain families of all kinds, and have a positive, lasting effect on society.

collections:
  AniDB Popular:
    summary: A collection of Popular Anime on AniDB
    anidb_popular: 30
    template:
      - name: customsync
      - name: chart_shared
        key: anidb

  Common Sense Selection:
    template:
      - name: css
      - name: customsync
      - name: chart_shared
        key: commonsense

  StevenLu's Popular Movies:
    summary: A collection of StevenLu's Most Popular Movies
    stevenlu_popular: true
    template:
      - name: customsync
      - name: chart_shared
        key: stevenlu
        check_library: movie

  Top 10 Pirated Movies of the Week:
    mdblist_list: https://mdblist.com/lists/hdlists/top-ten-pirated-movies-of-the-week-torrent-freak-com/
    summary: TorrentFreak.com's Weekly Top Ten Pirated Movies
    template:
      - name: customsync
      - name: chart_shared
        key: pirated
        check_library: movie
